### ISSUE TITLE
Bu dosya hepten dağılmış

### ISSUE THREAD

**Issue by ysn1453** [ipara/ipara-json_xml#5]
https://github.com/ipara/ipara-json_xml/blob/f0fdc5ae81210ea28524ec3745822fc95a559581/C%C3%BCzdandaki%20Kartlar%C4%B1%20Getir/Response.json#L5

**Comment by oznksoy** [comment]
Yasin Selam,

Gerekli biçimlendirmeleri yaptık. Destek için teşekkürler.
